export default function TC(){
    return(
      <div className="w-full text-md">
        <div className="font-bold mb-4">Terms & Condition</div>
        <div className="mt-4">Please read the following terms and conditions before registering on, accessing, or using the website value1.in (“this Website”). This Website and this App are owned and operated by Value1 in MOU with Augmont Goldtech Private Limited (Formerly Augmont Precious Metals Private Limited).  </div>
        <div className="mt-4">We, Augmont Goldtech Private Limited and/or our designated affiliates (jointly “Augmont”) provide the Platform features to you, the user, subject to your acceptance of the following Terms and Conditions of Access and Use, constituting an agreement between us (“Agreement”). If you continue to use the Platform or communicate with us, you will be deemed to have accepted these Terms and Conditions of Access and Use. Please read these Terms and Conditions of Access and Use carefully. In addition, when you use any current or future Augmont service or business you will also be subject to the guidelines, terms and agreements applicable to such service or business (“Specific Terms”). If the Terms and Conditions of Access and Use are expressly inconsistent with such Specific Terms, the Specific Terms will prevail. Augmont may revise these Terms and Conditions of Access and Use from time to time and at any time, without notice to you. If you do not agree to be bound by these Terms and Conditions of Access and Use, as modified from time to time, you should leave the Platform immediately.  </div>
        <div className="mt-4">The section titles in these Terms and Conditions of Access and Use are for convenience only and have no legal effect.  </div>
      
        <div className="mt-4 font-semibold uppercase">ACCEPTANCE OF DISCLAIMERS AND EXCLUSIONS </div>
        <div className="mt-4">You acknowledge that the disclaimers and exclusions of liability mentioned in these Terms and Conditions of Access and Use represent a fair and reasonable allocation of the risks and benefits of the Agreement between you and us, taking all the relevant factors into consideration. You agree that these disclaimers and limitations shall be enforceable to the fullest extent permitted by applicable law. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Platform or these Terms and Conditions of Access and Use must be filed within one (1) year after such claim or cause of action arose or be forever barred. These Terms and Conditions of Access and Use shall be read in conjunction with the Business Rules of Augmont and of the Platform, as available on the Platform. Augmont may revise these Business Rules from time to time and at any time, without notice to you..  </div>

        <div className="mt-4 font-semibold uppercase">COPYRIGHT</div>
        <div className="mt-4">All content included on the Platform such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of Augmont or its content suppliers and is protected by international copyright laws. All software used on this site is the property of Augmont or its software suppliers and is protected by international copyright laws. The content of the Platform cannot be copied, reproduced, republished, uploaded, posted, transmitted, or distributed for any non-personal use without the prior written approval of Augmont. Graphics, logos, page headers, button icons, scripts, and service names contained in or features on the Platform are trademarks or trade dress of Augmont. Augmont’s trademarks may not be used in connection with any other product or service, in any manner that is likely to cause confusion, disparage or discredit regarding Augmont and its products and services. All trademarks not owned by Augmont that appear on this site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by Augmont.  </div>

        <div className="mt-4 font-semibold uppercase">DISCLAIMER OF WARRANTIES</div>
        <div className="mt-4">The Platform and all information, content, materials, products (including software), and services included on or otherwise made available to you through the Platform are provided by Augmont on “as is” and “as available” basis, unless otherwise specified in writing. Augmont makes no representations or warranties of any kind, express or implied, as to the operation of this site or the information, content, materials, products (including software), or services included on or otherwise made available to you through this site, unless otherwise specified in writing. You expressly agree that your use of this site is at your sole risk. To the full extent permissible by applicable law, Augmont disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. Augmont does not warrant that this site; information, content, materials, products (including software), or services included on or otherwise made available to you through this site; their servers; or electronic communications sent from Augmont are free of viruses or other harmful components. Augmont will not be liable for any damages of any kind arising from the use of this site or from any information, content, materials, products (including software), or services included on or otherwise made available to you through this site, including, but not limited to direct, indirect, incidental, punitive, and consequential damages, unless otherwise specified expressly in writing. </div>

        <div className="mt-4 font-semibold uppercase">DISPUTES</div>
        <div className="mt-4">Any dispute or claim relating in any way to your visit to the Platform or to products or services sold or distributed by Augmont or through the Platform will be resolved first by arbitration. The Indian Arbitration and Conciliation Act of 1996 applies to this agreement. To begin an arbitration proceeding, you must send a letter requesting arbitration and describing your claim in detail to our address available on the Platform. The arbitration will be conducted in Mumbai by an independent arbitrator appointed by Augmont. The costs of arbitration proceedings will be borne by the party so instructed by the arbitrator, on the merits of the case. We each agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated or representative action.  </div>

        <div className="mt-4 font-semibold uppercase">ELECTRONIC COMMUNICATIONS  </div>
        <div className="mt-4">When you visit the Platform or send emails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We may communicate with you by one or more letters, e-mail, SMS, or by posting notices on the Platform. You agree that all the agreements, notices, disclosures, and other communications that we provide to you electronically satisfy all the legal requirements that such communications be in writing.  </div>

        <div className="mt-4 font-semibold uppercase">EQUIPMENT</div>
        <div className="mt-4">You shall procure and maintain all communication and other equipment necessary to access the Platform and the costs of any such equipment and communication connections or use, including any applicable taxes, shall be borne solely by you. You are responsible for operating your equipment used to access the Platform.  </div>

        <div className="mt-4 font-semibold uppercase">FINANCIAL TRANSACTIONS AND TAXES </div>
        <div className="mt-4">If you wish to make any financial transactions on the Platform, including paying for products or services, you may be asked for payment information. You agree that all information you provide is accurate, complete, and current and that you will pay all charges owed, including any applicable taxes. You agree that you are solely responsible for any personal income reporting and tax payments required of you by applicable government authorities.  </div>

        <div className="mt-4 font-semibold uppercase">GOVERNING LAW AND JURISDICTION</div>
        <div className="mt-4">By visiting the Platform, you agree to be bound by the applicable Indian laws and State laws, including those pertaining to taxation. This Agreement has been executed and delivered in India, and its interpretations, validity, and performance shall be construed and enforced in accordance with the laws of the Republic of India, without regard to principles of conflict of laws, and shall be subject to the exclusive jurisdiction of courts at Mumbai, India.  </div>

        <div className="mt-4 font-semibold uppercase">INDEMNIFICATION</div>
        <div className="mt-4">You agree to indemnify, defend and hold Augmont harmless from all claims, damages and expenses, (including attorney’s fees) made by any third party arising out of your content, your use of the Platform, your connection to the Platform, your violation of this Agreement, our Terms and Conditions of Access and Use or our business policies, and the development, operation, maintenance, use and contents of this Platform.  </div>

        <div className="mt-4 font-semibold uppercase">INDEPENDENT INVESTIGATION</div>
        <div className="mt-4">You acknowledge that you have read these Terms and Conditions of Access and Use and agree to them in the entirety. You understand that we may at any time (directly or indirectly) solicit member referrals on terms that may differ from those contained in these Terms and Conditions of Access and Use. You have independently evaluated the desirability of associating with the Platform or of participating in its programs or of availing its services and/or products, and are not relying on any representation, guarantee, or statements other than as set forth in these Terms and Conditions of Access and Use.  </div>

        <div className="mt-4 font-semibold uppercase">LICENSE AND SITE ACCESS</div>
        <div className="mt-4">Augmont grants you a limited license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with the express written consent of Augmont. This license does not include any resale or commercial use of this site or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this site or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without the express written consent of Augmont. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of Augmont without its express written consent. You may not use any meta tags or any other “hidden text” utilizing Augmont’s name or trademarks without the express written consent of Augmont. Any unauthorized use terminates the permission or license granted by Augmont. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the Platform so long as the link does not portray Augmont, or its products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any Augmont logo or other proprietary graphic or trademark as part of the link without express written permission.  </div>

        <div className="mt-4 font-semibold uppercase">LIMITATION OF LIABILITY  </div>
        <div className="mt-4">You expressly agree that the use of the Platform is at your sole risk. While we will take all reasonable precautions to ensure uninterrupted and error-free operations, your access and use of the Platform are at your sole risk. The service is provided on an “as is” and “as available” basis. We and our licensors, suppliers, vendors, parent, holding, subsidiary and related companies, affiliates, officers, agents, and employees expressly disclaim all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement. In no event shall Augmont be liable for any direct, indirect, incidental, special, punitive, consequential damages, or any damages whatsoever, including, but not limited to, damages for loss of profits, goodwill, use, data, or other intangible losses resulting from: </div>
        <ul className="list-disc list-inside">
          <li className="mt-4">The use or the inability to use our services or access content,  </li>
          <li className="mt-4">The cost of procurement of substitute goods and services resulting from transactions entered into through or from the Platform, </li>
          <li className="mt-4">The unauthorized access to or alterations of your transmissions or data,  </li>
          <li className="mt-4">Statements or conduct of any third party on the service, or  </li>
          <li className="mt-4">Any other matter relating to any service or product offered, delivered, or agreed to be delivered, even if Augmont has been advised of the possibility of damages.  </li>
        </ul>

        <div className="mt-4 font-semibold uppercase">OTHER BUSINESSES</div>
        <div className="mt-4">For your convenience, the Platform may provide links to the sites of affiliated companies and certain other businesses, which may not be in our control. You acknowledge that Augmont does not endorse these linked sites (even if they pop up in a frame) or any links contained in these linked sites. We are not responsible for examining or evaluating, and we do not warrant the offerings of, any of these businesses or individuals or the content of their website. Augmont does not assume any responsibility or liability for the actions, product, and content of all these and any other third parties. You should carefully review their privacy statements and other conditions of use. </div>

        <div className="mt-4 font-semibold uppercase">PATENTS  </div>
        <div className="mt-4">One or more patents owned by Augmont may apply to the Platform and to the features and services accessible via the Platform. Portions of the Platform may operate under the license of one or more patents.</div>

        <div className="mt-4 font-semibold uppercase">PRICING  </div>
        <div className="mt-4">Except where noted otherwise, the prices displayed for products on the Platform represent the value of the respective product. For certain transactions, you shall bear fees and charges in addition to payment for prices displayed on the Platform. Such additional fees and charges shall be as are stated on the Platform. Please pay attention to the details of your transactions, because your total price for a transaction may include taxes, fees and shipping costs, which you are responsible for paying.  </div>
        <div className="mt-4">With respect to services provided or products sold by Augmont, we cannot confirm the cost of a service or the price of a product until you order. Despite our best efforts, a small number of the items in our catalogue may be mispriced. If an item’s correct price is higher than our stated price, we will, at our discretion, either contact you for instructions before shipping or cancel your order and notify you of such cancellation. </div>
        
        <div className="mt-4 font-semibold uppercase">PRIVACY  </div>
        <div className="mt-4">The Platform is strongly committed to your right to privacy and to keeping your information secure. We collect your personal information on a need-to-know basis. Personal information includes, but is not limited to, first and last name, physical address, e-mail address, phone number, birth date, and any other information that itself identifies or when tied to the above information, may identify you as a specific individual. Additionally, Augmont may require you to provide additional information and documents for meeting its Know-Your-Client guidelines. The Platform does not collect personally identifiable information about you except when you specifically and knowingly provide it. Augmont uses your personally identifiable information also to operate the Platform and offer its services and to inform you of new features, services, and products from Augmont. </div>
        <div className="mt-4">Augmont may carefully select other companies to send you information about their products or services which are related to the Platform but are not necessary to its operation (an “Extended Service”). You would be provided the option to decline the Extended Service. </div>
        <div className="mt-4">Augmont may disclose your personal information if required to do so by law or in the good-faith belief that such action is necessary: (a) to conform to the edicts of the law or comply with legal process served on Augmont; (ii) to protect and defend the rights or property (including intellectual property) of Augmont and/or of the Platform or (iii) to act under exigent circumstances (as Augmont may, in its sole decision decide) to protect the personal safety of users of the Platform, Augmont, or the public. </div>
        <div className="mt-4">The Platform may have features that provide for users to disclose their identities and communicate with other users. Your use of such features and disclosure of any personal details (e.g. e-mail address, mobile numbers) by you through these features are at your sole risk, and Augmont accepts no responsibility for the same.</div>

        <div className="mt-4 font-semibold uppercase">PRODUCT DESCRIPTIONS  </div>
        <div className="mt-4">Augmont attempts to be as accurate as possible. However, Augmont does not warrant that product descriptions or other content of this site is accurate, complete, reliable, current, or error-free. If a product offered by Augmont is not as described, your sole remedy is to return it in unused condition for a replacement under the provisions of our Replacement Policy.  </div>

        <div className="mt-4 font-semibold uppercase">RETURNS, REPLACEMENT AND TITLE  </div>
        <div className="mt-4">Augmont does not take title to returned items until the item arrives at our designated address. For more information about our returns and replacement, please see our Replacement Policy. </div>

        <div className="mt-4 font-semibold uppercase">REVIEWS, COMMENTS, COMMUNICATIONS, AND OTHER CONTENT  </div>
        <div className="mt-4">You may post reviews, comments, photos, and other content and submit suggestions, ideas, comments, questions, or other information to the Platform, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of spam. You may not use a false e-mail address or mobile number, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. Augmont does not regularly review posted content, but reserves the right (but has no obligation) to remove or edit such content, at its sole discretion.  </div>
        <div className="mt-4">If you do post content or submit material, and unless we indicate otherwise, you grant Augmont a nonexclusive, royalty-free, perpetual, irrevocable, and fully sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant Augmont and its sub-licensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify Augmont for all claims resulting from content you supply. Augmont has the right but not the obligation to monitor and edit or remove any activity or content. Augmont takes no responsibility and assumes no liability for any content posted by you or any third party.  </div>

        <div className="mt-4 font-semibold uppercase">SITE POLICIES, MODIFICATION, AND SEVERABILITY</div>
        <div className="mt-4">Please review our other policies posted on this site. These policies also govern your visit to the Platform. We reserve the right to make changes to our site, policies, and these Terms and Conditions of Access and Use at any time. If any of these Terms and Conditions of Access and Use is deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall be modified so as to give effect to the economic intent of such impugned provision, and shall not affect the validity and enforceability of the remaining Terms and Conditions of Access and Use.  </div>

        <div className="mt-4 font-semibold uppercase">TERMINATION  </div>
        <div className="mt-4">Augmont reserves the right to discontinue, in whole or in part, any portion of the Platform services or programs with or without notice. This discontinuation may relate to all users, certain groups of users, or to certain individual users.  </div>
        <div className="mt-4">This Agreement and the license rights granted hereunder shall remain in full force and effect unless terminated or canceled for any of the following reasons: (a) immediately by Augmont for any unauthorized access or use by you; (b) immediately by Augmont if you assign or transfer (or attempt to do so) any rights granted to you under this Agreement; (c) immediately if you violate any of the other terms and conditions of Terms and Conditions of Access and Use. Termination or cancellation of this Agreement shall not affect any right or relief to which Augmont may be entitled at law or in equity. Upon termination of this User Agreement, all rights granted to you will terminate and return to Augmont.  </div>

        <div className="mt-4 font-semibold uppercase">VOID WHERE PROHIBITED</div>
        <div className="mt-4">Although the Platform is accessible worldwide, not all products or services discussed or referenced on the Platform are available to all persons or in all geographic locations or jurisdictions. The Platform reserves the right to limit the provision of any product or service to any person, geographic area, or jurisdiction it so desires, in its sole discretion and to limit the quantities of any such product or service that it provides. Any offer for any product or service made on the Platform is void where prohibited.  </div>

        <div className="mt-4 font-semibold uppercase">YOUR ACCOUNT  </div>
        <div className="mt-4">If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. Augmont does not offer services or sell products to parties under the age of 18 years. Augmont reserves the right to refuse service, terminate accounts, remove or edit content, or cancel orders and instructions at its sole discretion.  </div>

        <div className="mt-4 font-semibold uppercase">ACCOUNT</div>  {/*in complete content*/}
        <div className="mt-4"></div>

        <div className="mt-4 font-semibold uppercase">ELIGIBILITY  </div>
        <div className="mt-4">You may use the Platform only if you are an Indian citizen, residing in India, and are eligible to enter into contracts under Indian law. Non-Indian citizens and non-resident Indians cannot participate on the Platform at present.  </div>

        <div className="mt-4 font-semibold uppercase">YOUR REGISTRATION OBLIGATIONS  </div>
        <div className="mt-4">In consideration of your use of the Platform, you agree to:</div>
        <ul className="list-disc list-inside">
          <li className="mt-4">Provide true, accurate, current, and complete information about yourself as prompted by the registration form required by the Platform (such information being the “Registration Data”), and</li>
          <li className="mt-4">Maintain and promptly update the Registration Data to keep it true, accurate, current, and complete. </li>
        </ul>
        <div className="mt-4">In addition, if required you fill and sign all forms and documents which form part of your account opening kit, and supply us with all the relevant legal documents and financial information which law requires us to maintain. You warrant and represent that all information that you supply to us is accurate and truthful. You also expressly authorize Augmont to obtain reports concerning your credit standing and business conduct. </div>
        <div className="mt-4">You can open an augmont account with us by entering your mobile number and verifying the same with the OTP sent to your mobile number.  </div>
        <div className="mt-4">Notwithstanding the foregoing, we may provide you with access to some parts of the Platform without you registering as a user. In that case, your identification is based on other means of identification that we deem appropriate. You warrant and represent that all information provided for this other means of identification is accurate and truthful. You further agree that such information may be collected and disclosed to us and used in accordance with these Terms and Conditions of Access and Use.  </div>

        <div className="mt-4 font-semibold uppercase">DISAPPROVAL OF APPLICATION  </div>
        <div className="mt-4">If you provide any information that is untrue, inaccurate, not current or incomplete, or Augmont has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Augmont has the right to suspend or terminate your account and refuse any and all current or future use of the Platform (or any portion thereof) without any liability to you.  </div>

        <div className="mt-4 font-semibold uppercase">ACCOUNT SECURITY  </div>
        <div className="mt-4">Upon completing the registration process with the Platform, the system will create a unique customer id for you. You are responsible for maintaining the confidentiality of the account, and are fully responsible for all activities that occur under your account. You agree to (a) immediately notify Augmont of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session.  </div>

        <div className="mt-4 font-semibold uppercase">TERMINATION OF ACCOUNT  </div>
        <div className="mt-4">You agree that Augmont, in its sole discretion, may terminate your password, account, or your use of the Platform. Augmont may terminate your Account and remove any content within the Platform for any reason, including, without limitation, if Augmont, in its sole opinion, believes that you have violated or acted inconsistently with the letter or spirit of these Terms and Conditions of Access and Use. Augmont may also, in its sole discretion and at any time, discontinue the Platform, or any part thereof, without notice. You may also request Augmont to terminate your account with us by sending an email to the customer help desk from your registered email id. You agree that any termination of your access to the Platform under any provision of these Terms and Conditions of Access and Use may be effected without prior notice, and acknowledge and agree that Augmont may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or to the Platform. Further, you agree that Augmont shall not be liable to you or any third party for any termination of your access to the Service. However, on such termination, Augmont shall, based on the request from the customer, deliver the bullion lying in the vaults in the form of coins and/or bars, sell the fractional parts and return the net amount of money standing to the credit of your Account</div>

        <div className="mt-4 font-semibold uppercase">INVESTMENT DECISIONS  </div>
        <div className="mt-4">Augmont may publish research and opinions on the Platform, for your information. You may not rely on any such information for forming your investment decisions. You acknowledge that Augmont or the Platform and its officers, directors, employees, agents, and affiliates will have no liability with respect to transactions in or for your Account and your investment decisions.</div>

        <div className="mt-4 font-semibold uppercase">OPERATIONS</div> {/* incomplete */}
        <div className="mt-4"></div>

        <div className="mt-4 font-semibold uppercase">OVERVIEW  </div>
        <div className="mt-4">Through the Platform, Augmont shall facilitate the buy and sell of Gold and Silver (Bullion). All such buy and sell transactions are final and non-reversible.  </div>
        <div className="mt-4">Augmont shall provide buy/sell quotes for the prices of Bullion, which shall be linked, based on a formula, to the prices of gold and silver in the spot market. You may buy any quantity of Bullion through the Platform, subject to policies framed in this regard by Augmont. Augmont shall issue an invoice with Bullion (as the case may be) purchased by you. The Bullion purchased will be delivered to and stored with a custodian in a vault on your behalf and at your request by default. The cost of insurance of Bullion will be borne by Augmont.  </div>
        <div className="mt-4">You shall have the option to (a) sell gold/silver from your Platform account back to Augmont at the prices shown on the Platform at the time of sale, or (b) request for the delivery of the gold/silver in the form of coins and bars online from us or (c) transfer the gold/silver to another account.</div>

        <div className="mt-4 font-semibold uppercase">BUSINESS DEPOSIT</div>
        <div className="mt-4">You can transfer business the deposits in your account by using Internet banking, electronic transfer, cheque, demand draft, and debit card or wallet. Business Deposit will be credited in your account only after the funds are cleared.  </div>
        <div className="mt-4">When you buy gold/silver through your Account on the Platform, you can use the amount of the business deposit towards the amount payable for the purchase in your Account. Similarly, when you sell gold/silver from your Account on the Platform, the amount of the transaction can be added to the business deposit or bank account as per your request in your Account. No interest would be payable on the business deposits maintained by you in the Account or with Augmont. You may withdraw a part or the entire business deposit in your Account upon request to Augmont. The withdrawal may be effectuated by such means as Augmont may decide at its sole discretion. Such means may include electronic transfer of funds to your bank account and payment through cheque.</div>
        <div className="mt-4">While it is unlikely, there could be a negative deposit in your Account due to reasons such as charges debit, inadvertently processing buy orders exceeding the business deposit, technical issue etcetera. In such a case, you would promptly transfer funds to your Platform Account to the extent of the negative balance. If payment is not received within a reasonable time, your Account may be closed, without prior notification. In such an event, you will be liable for any resulting losses and all associated costs incurred by Augmont.  </div>

        <div className="mt-4 font-semibold uppercase">PLACEMENT OF ORDERS</div>
        <div className="mt-4">The market prices of bullion shown on the Platform would be an invitation to offer to all eligible account holders. An order legitimately placed by an eligible Account holder would constitute an offer for purchase or sale of the Gold or Silver, as the case may be. Augmont may accept or reject such an offer, at its discretion.  </div>
        <div className="mt-4">Though orders would usually be attended to within seconds, certain orders, at Augmont’s discretion, may be subject to manual review and entry, which may cause delays in the processing of your orders. You also accept that you will receive the price at which your order executes in our systems, which may be different from the price at which Gold or Silver is trading at when you enter your order into our system. You acknowledge that you cannot modify an order once placed and that orders may get executed at a price significantly unfavorable to you, depending upon market fluctuations.  </div>

        <div className="mt-4 font-semibold uppercase">AGENTS</div>
        <div className="mt-4">In order to ensure smooth and efficient operations, Augmont may appoint one or more agents (including a Commission agent) on your behalf, from time to time. If required, you agree to ratify such appointment(s) retrospectively. All agents shall have the right to terminate their appointment at any time, without prior notice to you.</div>
        <div className="mt-4">The Commission agent appointed by Augmont on your behalf shall be appointed for a limited purpose of representing you and acting on your behalf – to make deliveries/constructive deliveries, make and receive payments for trades done by you on the Platform. Your acceptance of these Terms and Conditions of Access and Use shall form consideration for the appointment of the Commission Agent.  </div>
        <div className="mt-4">All payments from and to you shall be appropriated through the Commission agent as and when required. Notwithstanding the above mechanism, all statutory liability (including GST and other applicable taxes) shall always be to your account, and you shall indemnify the Commission Agent for any losses suffered for acting as your agent.  </div>

        <div className="mt-4 font-semibold uppercase">REQUEST DELIVERY </div>
        <div className="mt-4">The Platform offers services for users who wish to request the delivery of the gold and silver bought by the users and lying in the vaults. The Platform displays the articles that are available for delivery along with the making and delivery charges for each article. Some items may appear slightly larger or smaller than the actual size due to screen defaults and photography techniques. Sometimes the items may be represented larger than the actual size in order to clearly show details or smaller than the actual size in order to show the entire item. The Company shall not be liable for any legal action on this account. All the details regarding the product shall be clearly displayed on the Platform.  </div>
        <div className="mt-4">This facility shall be available to all registered users of the Platform. Any registered user who wishes to request delivery of the gold and silver from the Platform can choose from the selection of Jewellery and Coins and Bars available on the Platform and add the item to the shopping cart.  </div>


        <div className="mt-4">Product</div>
        <div className="mt-4">Infrequently, data may be inaccurately displayed on the Platform due to system errors. Augmont reserves the right to correct any and all errors when they do occur and Augmont shall not honour inaccurate or erroneous prices. The delivery charges on the Platform are also subject to change without notice. For any order the delivery charges on the day the order is confirmed prevails. The delivery charges of the products listed on the Platform are fixed and not negotiable.  </div>

        <div className="mt-4">Delivery  </div>
        <div className="mt-4">Delivery shall be made by the Company/courier agent at your doorstep. All the items shall be delivered directly to such person and under any circumstances whatsoever, the member cannot change the recipient details after the order is processed. The member has the option to change the shipping address, before the product is actually shipped. In the event the member wishes to change the shipping address he/she has to log in to his/her user account on the Platform and click on the “Change Shipping Address” button next to the shipping address and change the address or can request the helpdesk via email. However, the Shipping Address cannot be changed once the order is processed. </div>
        <div className="mt-4">The recipient accepting delivery should carefully examine the package delivered and shall not accept deliveries where the packaging has been tampered with. The recipient receiving the delivery also has the option to open the package and check its contents before accepting the delivery or signing the delivery receipt. They shall not accept deliveries, where they find that the box is empty or the contents are damaged or the contents are not in accordance with the order placed.</div>
        <div className="mt-4">The recipient, upon signing the delivery receipt, acknowledges the receipt of the product in terms of the order placed with the Company. The Company is not liable to the Customer/recipient for any refund/replacement, under any circumstance, for any subsequent complaints with respect to such deliveries If the recipient is not available at the time of delivery, the Company/courier agent shall try and deliver the item thrice before returning the same to Augmont. All costs for the re-shipment and handling in the case of non-delivery to the Customer shall be chargeable to the Customer.  </div>


        <div className="mt-4">Return & Replacement Policy</div>
        <div className="mt-4">In the event you receive a damaged / defective article or an article that does not comply with the specifications as per your original order, you are required to get in touch with the customer service team.</div>
        <div className="mt-4">Upon receiving your complaint, Augmont shall verify the authenticity and the nature of the complaint. If Augmont is convinced that the complaint is genuine, Augmont shall provide a free replacement. However, in the event of frivolous and unjustified complaints regarding the quality and content of the products, Augmont reserves the right to pursue necessary legal actions against you and you will be solely liable for all costs incurred by Augmont in this regard. </div>
        <div className="mt-4">Before accepting the shipment of any product, kindly ensure that the product’s packaging is not damaged or tampered with. If you observe that the package is damaged or tampered with, we request you not to accept the delivery and inform Augmont at the earliest. The return process of the product may be restricted by Augmont depending on the nature and category of the product. </div>

        <div className="mt-4">Refunds  </div>
        <div className="mt-4">Any refunds due by Augmont to the user for non-availability of articles shall be credited to the registered user’s business deposits balance with Augmont.</div>

        <div className="mt-4 font-semibold uppercase">INTERMEDIARIES</div>
        <div className="mt-4">Augmont may appoint Intermediaries and Distributors who shall assist us in distributing our products to you. Augmont shall communicate all the transaction details to you directly by means of emails, SMS and any other medium. and it is your responsibility to ensure that you receive this communication. When you visit the Platform or send emails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We may communicate with you by one or more letters, e-mail, SMS or, by posting notices on the Platform. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy all legal requirements that such communications be in writing. Augmont shall not be responsible to you in the event of default or any wrongful, dishonest, criminal, fraudulent act or wilful misconduct or gross negligence on the part of these Intermediaries. However, you shall immediately inform Augmont on the occurrence of such an event through emails/telephone/fax or any other convenient means. The activities of the Intermediaries and its personnel/representative(s) shall not be construed to be activities of Augmont.</div>

        <div className="mt-4 font-semibold uppercase">TRANSFER THROUGH SUCCESSION </div>
        <div className="mt-4">Any gold/silver lying in the vault, and business deposit is non transferable unless specifically allowed by Augmont. However, in case of death or insanity, Augmont shall transfer such gold/silver, and advance balance to your legal heir(s) after the required due diligence, and your legal heir(s) shall be regarded as the Registered User thereafter. </div>

        <div className="mt-4 font-semibold uppercase">FORCE MAJEURE</div>
        <div className="mt-4">In case of the inability of Augmont to make deliveries of coins, bars and jewelry bullion due to reasons beyond its control, Augmont may require that the deliveries be effectuated through specific modes, including through local agents/jewelers. In such a case, you agree to bear any additional costs and fees necessary for the delivery to be complete. </div>

        <div className="mt-4 font-semibold uppercase mb-3">BUSINESS RULES</div>
        <div className="mt-4 font-semibold uppercase">INTRODUCTION  </div>
        <div className="mt-4">These rules are the business rules of the website <a href="www.value1.in" className="text-gold-500 no-underline">www.value1.in</a> owned and operated by Value1, OOSH Learnings Private Limited in MOU with Augmont Goldtech Private Limited and/or its affiliates (jointly “Augmont”). For the sake of brevity, these business rules are referred to as “Business Rules”. These Business Rules are to be read in conjunction with the other applicable provisions, articles, terms, conditions, stipulations, and rules of Augmont and the Platform. We, Augmont, provide certain services and products to you, the user, subject to these Business Rules. Augmont may revise these Business Rules from time to time and at any time, without notice to you.</div>
        <div className="mt-4">The section titles in these Business Rules are for convenience only and have no legal effect.</div>

        <div className="mt-4 font-semibold uppercase">OVERVIEW  </div>
        <div className="mt-4">The Platform shall facilitate purchase and sale of Gold and Silver with each of its specific users (such users are referred to as “Registered Members”). The Bullion can be bought and sold online using the Platform’s buying/selling platform. You can buy/sell any quantity of gold and silver on the Platform. The value of Bullion is in INR terms and excludes GST and other applicable taxes. Both Buy and Sell prices of Bullion will be quoted exclusive of GST. Augmont shall raise e-invoices for the Bullion sold.  </div>
        <div className="mt-4">Augmont shall provide buy/sell rates of Bullion, Registered Members shall have the option to either sell the Bullion to Augmont at the prevailing market prices or allow the custodian to store the bullion in the designated vaults or to request for the delivery of the Gold/Silver bought in the form of coins and bars online with us.  </div>

        <div className="mt-4 font-semibold">Business Days and Hours</div>
        <div className="mt-4">The Platform shall facilitate buying and selling of Bullion on all days of the week 24/7. The customer service shall however be available only during business hours. In the event of the breakdown of the system or communication link is severe, the Platform will see some downtime and will be up and working after the problem is resolved. </div>
        <div className="mt-4">Other operations such as transfer of business deposits, request delivery function, shop, change of registered address, registration of new SIP, etc can generally be conducted on any day and at any time throughout the year. The processing of these operations will however happen only during working days and hours.  </div>

        <div className="mt-4 font-semibold uppercase">ACCOUNT OPERATIONS  </div>
        <div className="mt-4">Augmont and the Platform reserve the right to accept or reject a member’s application for membership, without providing any reason for its decision. All Registered Members shall be subject to and shall follow the rules which are made applicable by Augmont and/or the Platform from time to time. The unique id provided to the member cannot be changed.  </div>

        <div className="mt-4 font-semibold uppercase">TRANSFER OF FUNDS  </div>
        <div className="mt-4">A Registered Member’s account (“Account”) shall always reflect the business deposit balance in his Platform account and the balance of net bullion purchased by him/her lying in the vault. The Registered Member may transfer business deposit money with Augmont and withdraw the same from the Platform Account as and when he/she requires. </div>
        <div className="mt-4">By clicking on the ’Deposit Funds’ tab on the website, you will be provided with various options for depositing advance money like Net Banking, Debit Card, RTGS, NEFT, NACH, Wallet, Cheque, and DD. By clicking on Net Banking or Debit Card, you will be redirected to the online payment gateway. You can, then, transfer such business deposit to Augmont and the same will reflect in your Platform account immediately. In case of payments done by RTGS, NEFT, Cheque, or DD, your Platform account will be credited within 48 hours of the receipt of such business deposit by Augmont. Surplus funds lying in an Platform account of a Registered Member shall remain with Augmont. The Registered Member may place a request for withdrawal of a specific amount from the business deposit with Augmont. Augmont shall transfer such amount to the bank account of the concerned Registered Member within seven working days from the date of receipt of such withdrawal request. In case such surplus funds are lying with Augmont for a period of more than 180 days, the system shall generate a withdrawal request of such surplus funds and the same shall be transferred to the bank account of the concerned Registered Member within seven working days However, Bullion India may deduct charges for generating such withdrawal requests as per its discretion. You can not withdraw the amount from your account to your bank account without performing any buy and sell transactions.  </div>

        <div className="mt-4 font-semibold uppercase">BUYING / SELLING </div>
        <div className="mt-4">The common parameters with respect to buying/selling are as follows:</div>
        <ul className="list-disc list-inside">
          <li className="mt-4">Buy/Sell Price Spreads: The Platform will continuously provide buy/sell prices for the gold/silver on the platform. The buy/sell prices and the spread between them could change on the basis of various factors including price volatility, supply factors, external market conditions, etc.  </li>
          <li className="mt-4">Price Quote Requests:  Registered Members could request market price quotes for gold/silver they wish to buy/sell in, and could buy and sell at the quoted price by placing orders. Currently this facility is not available.</li>
          <li className="mt-4">An order which does not conform to the specifications laid down by Augmont and the Platform shall be considered void. </li>
          <li className="mt-4">Quantity of Gold/Silver earned through any promotional offers on Augmont app is non-saleable. However, a customer can request physical delivery of this Gold/Silver by paying nominal making and delivery charges.</li>
          <li className="mt-4">Cashback or amount received through any promotional on the Augmont app cannot be withdrawn. However, this can be used to purchase Gold/Silver or to request physical delivery of Gold/Silver on the Augmont app.</li>
          <li className="mt-4">In case you face any technical, network or unexplained issues during the processing of your transaction, your amount will be refunded back to your account. You are requested to reinitiate the transaction during such scenarios. Augmont will not be responsible for any difference in the rates of any product.  </li>
        </ul>

        <div className="mt-4 font-semibold">Buying/selling Functions  </div>
        <div className="mt-4">Following functions can be performed by the Registered member:  </div>
        <ul className="list-disc list-inside">
          <li className="mt-4">Buy: A Registered member can buy gold and silver in any quantity in grams up to four decimals. There is no upper limit on purchase quantity. The customer shall pay the amount using a payment gateway immediately at the time of buying the gold/silver. Upon successful execution of buying, the purchased Bullion will reflect in the Registered Member’s Platform Account. The Registered Member can also utilize his/her business deposit for the buying of Gold and Silver. On execution of every buy order, Augmont / the Platform will purchase the corresponding quantity of physical Bullion(as the case may be) and deliver it to the custodian who stores their bullion in the designated secured vaults. </li>
          <li className="mt-4">Hold: The Bullion purchased by a Registered Member can be stored with the custodian in a designated vault.  </li>
          <li className="mt-4">Sell:  The gold and silver held by a Registered Member can be sold back to Augmont in any quantity in grams up to four decimals. A Registered member can sell only the bullion which is lying in the vault on his/her behalf. Upon successful execution of the sale, the sold quantity of Bullion will be deducted from the Registered Member’s Platform Account and the appropriate amount of funds will be added to her/his Account. The gold or silver bought cannot be sold within 48 hours from the time of buying.</li>
        </ul>

        <div className="mt-4 font-semibold uppercase">SYSTEMATIC INVESTMENT PLAN  </div>
        <ul className="list-disc list-inside">
          <li className="mt-4">Systematic Investment Plan (henceforth referred to as “SIP”) is a disciplined accumulation of Gold/Silver. The SIP enables the member to buy gold and silver of a certain fixed amount every month and accumulate Gold/Silver at periodic intervals at a “Configured Price”. </li>
          <li className="mt-4">The Configured Price for SIP shall be calculated by the Platform on every Business Day and shall be displayed on the Platform before 1 pm which shall be final and binding for everyone. A Business Day means any day other than Sunday or a day declared as a holiday under the Negotiable Instruments Act, 1881 or a day on which normal business could not be transacted due to storms, floods, strikes, riots, or any other events as Augmont may specify from time to time.  </li>
          <li className="mt-4">To start the SIP, the member needs to log in to his/her account, click on the SIP link and fill in a simple form specifying the choices and submit. After successfully submitting an SIP application, the member will get a confirmation SMS/email.  </li>
          <li className="mt-4">The member can start their SIP with the minimum amount of ₹ 1000 per month and can invest in multiples of ₹ 1000 thereafter.  </li>
          <li className="mt-4">The member gets an option to buy additional quantities of gold and silver in the existing SIP and the said quantity shall be added to the SIP quantity for the tenure. The member can choose the duration of this SIP which can range from 1 year to 10 years.  </li>
          <li className="mt-4">The member gets an option to choose the SIP date cycle from the four options viz. 5th/12th/19th/26th of every month. e.g. If the member submits the SIP application on the 7th October and selects the SIP cycle date as the 12th of each month, then the SIP will initiate on the 12th of October. However, if they choose the SIP cycle date as the 5th of each month, then the SIP start date will be the 5th of November.  </li>
          <li className="mt-4">One cannot change the amount of SIP, duration, and cycle date once the request is submitted. In order to change one has to terminate the existing SIP and register for a new one. There are no charges currently for doing the same.  </li>
          <li className="mt-4">The frequency of buying is once per month. So, if the member chooses the SIP amount to be ₹ 1000 per month in SIP, ₹ 1000 is utilized for purchasing the Gold/Silver.</li>
        </ul>
        <div className="mt-4">The Registered Member can request for termination of his existing SIP by contacting the customer help desk. SIP will be terminated only upon the completion of the current SIP cycle month. e.g. If the member has selected 5th of every month as his SIP cycle date and his SIP is active, and the member decides to exit the SIP on 10th of the month, the cycle will continue till 4th of next month and then terminate.  </div>
        <div className="mt-4">At the end of SIP tenure or on SIP termination, the member may sell the gold and silver at the market price displayed on the Platform. Alternatively the member can request for termination of his account with us in which case the gold and silver shall get sold at the market rate and the proceeds shall be remitted to the member’s bank account.  </div>
        <ul className="list-disc list-inside">
          <li className="mt-4">You may not sell Gold / Silver under SIP but you can request the delivery of the gold and silver accumulated during the tenure of the SIP. Alternately you may sell the gold and silver under the SIP at the end of the tenure.  </li>
          <li className="mt-4">In case you miss your monthly SIP installment, you will be given a grace period of 60 days. Within the grace period, if you do not transfer sufficient funds in your account, then your SIP may be treated as ’defaulted’ and your SIP may be irreversibly terminated.  </li>
          <li className="mt-4">The SIP is neither a financial product nor a deposit scheme but a disciplined method of accumulating Gold/Silver. Bullion India offers no investment advice or any assured returns while promoting the SIP.  </li>
        </ul>

        <div className="mt-4 font-semibold uppercase">REPLACEMENT POLICY  </div>
        <div className="mt-4">The following rules will apply regarding the replacement of articles delivered to the customers:  </div>
        <ul className="list-disc list-inside">
          <li className="mt-4">Replacement shall be sought in writing no later than three business days from date of delivery to the Registered Member;  </li>
          <li className="mt-4">Replacement shall be subject to the return of the delivered articles at Augmont’s office address stated for this purpose on the Platform;</li>
          <li className="mt-4">It shall be the responsibility of the Registered Member to ensure the safe delivery of articles to Augmont’s custody. Till such time that the receipt of Bullion is acknowledged as “received” by Augmont, the risk of loss of the article shall remain with the concerned Registered Member; </li>
          <li className="mt-4">Replacement shall be subject to handover of the delivered article in its original tamper-proof packing, if any, in an intact, un-opened, and non-mutilated condition. The decision of Augmont regarding the condition of the tamper-proof packing shall be final and conclusive;  </li>
          <li className="mt-4">While Augmont shall try to replace a returned piece with a close substitute, Augmont shall have the right to replace the returned piece with any piece which is similar in composition and equal in market value on the date of replacement (although not necessarily similar in shape or design) with the returned piece.  </li>
        </ul>

        <div className="mt-4 font-semibold">Taxes, brokerage, and other charges</div>
        <div className="mt-4">No brokerage will be charged to Registered Members for any buy and sell done by them. For each buy and sell conducted by a Registered Member, an e-invoice will be generated in the name of the Member. </div>
        <div className="mt-4">All taxes, duties, levies etcetera, as applicable, will be borne by the concerned Registered Member. Augmont shall not be responsible for such statutory taxes.  </div>
        
        <div className="mt-4 font-semibold uppercase">SYSTEMS  </div>
        <ul className="list-disc list-inside">
          <li className="mt-4">Operations on the Platform shall be conducted on an automated basis. Registered Members will be required to connect to the Platform over the Internet.  </li>
        </ul>
        <div className="mt-4">Operations on the Platform shall be allowed through suitable internet-connected devices of a Registered Member. Each registered member shall login with their respective augmont account by entering their mobile number. A registered member shall have non-exclusive permission to use the Platform in the ordinary course of business. A registered member shall not have any title, rights or interest with respect to the Platform, its facilities, software, and the information provided by Augmont and the Platform. The permission to use the Platform shall be subject to payment of such charges as Augmont and the Platform may prescribe from time to time.  </div>
        <div className="mt-4">A Registered Member shall not, by herself/himself or by through any other person(s), directly or indirectly:  </div>
        <ul className="list-disc list-inside">
          <li className="mt-4">Use the Platform for any purpose other than that approved and specified by the Platform;</li>
          <li className="mt-4">Copy, alter or modify the Platform, or make the Platform available to any other person; </li>
          <li className="mt-4">Use the Platform in any manner other than the manner as specified by Augmont;  </li>
          <li className="mt-4">Attempt – directly or indirectly – to decompile, disassemble or reverse engineer the Platform;  </li>
          <li className="mt-4">Publish, supply, show, or make available to any other person or reprocess, re-transmit, store or use the facilities of the Platform.  </li>
        </ul>

        <div className="mt-4 font-semibold uppercase">RISK MANAGEMENT SYSTEM  </div>
        <div className="mt-4">A Registered Member shall be allowed to operate upon compliance with all requirements of the Platform and of Augmont, including availability of 100% advance funds for buying. Neither the Platform nor Augmont shall provide a credit facility to the Registered Member. </div>

        <div className="mt-4 font-semibold uppercase">CONTROL & REPORTING SYSTEMS  </div>
        <div className="mt-4">The Platform may, at the decision of Augmont, cease operations in Bullion (Selected denominations of Gold and Silver as specified by the Platform) on the system for such an amount of time and for such reasons as it may deem fit in the best interests of the Registered Members and the overall markets. Orders, if any, in violation of an operation cease, will be rejected by the Platform.  </div>
        <div className="mt-4">Details of transactions conducted by Registered Members would be updated with the back-office systems of Augmont on a-real time basis. Registered Members can access the reports of their transactions over the Platform. Augmont may record such additional information about the buying and selling conducted on the Platform as it may consider relevant or necessary for its use. </div>

      </div>
    );
}